name: CI

on:
  push:
    branches: [ main, upgrade-openfhe ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgmp-dev \
            libmpfr-dev \
            libomp-dev \
            cmake \
            build-essential \
            python3-dev \
            python3-pybind11 \
            libpybind11-dev

      - name: Build & install OpenFHE & Python bindings
        run: make install

      - name: Run C++ tests & generate coverage
        run: make test

      - name: Verify Python bindings can import
        run: |
          python3 - << 'EOF'
          import openfhe
          print("openfhe version:", getattr(openfhe, "__version__", "n/a"))
          print("OK")
          EOF

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
